export const ADD_ANSWER = 'ADD_ANSWER';
export const ADD_ANSWER_LOADING = 'ADD_ANSWER_LOADING';
export const ADD_ANSWER_FAILED = 'ADD_ANSWER_FAILED';
export const ADD_ANSWER_SUCCESS = 'ADD_ANSWER_SUCCESS';